### ISSUE TITLE
test-junit, test-kotest 플러그인 의존성 추가

### ISSUE THREAD

**Issue by heesung6701** [TodayDoneDone/donedone-android#17]
### 체크리스트

- [X] 제목을 입력하셨나요?
- [X] Assignee를 지정하셨나요?
- [X] 프로젝트를 지정하셨나요?
- [X] 이 DEEP에 맞는 label을 지정하셨나요? (deep-automation, deep-library, deep-product)

### 요약

test-junit, test-kotest 플러그인을 추가하면 libs.versions.toml에 정의되어 있지 않아서 에러가 발생하고 있습니다.

### 필요한 이유

android test 코드 추가를 위해서 plugin에 정의된 의존성을 toml에 명시 합니다.

### 목표

android

### 계획

- [ ] test-junit 플러그인 의존성 추가
- [ ] test-kotest 플러그인 의존성 추가

### 논의 사항

각 의존성에 대해서 어떤 버전을 사용할 것인가?

**Comment by jisungbin** [comment]
제가 저걸 누락했더라구요!
추가 좋아요!

버전은 둘 다 최신 버전으로 하시져 👍🏼 

```toml
test-kotest = "5.6.2"
test-junit-core = "4.13.2"
test-junit-engine = "5.9.3"
```
